# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build React Client Stage'
  
  jobs: 
  - job: Build
    displayName: 'Build'
    
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'Install client packages'
      inputs:
        command: 'install'
        workingDir: 'client'

    - task: Npm@1
      displayName: 'Build client'
      inputs:
        command: 'custom'
        workingDir: 'client'
        customCommand: 'run build'
      
    - task: Npm@1
      displayName: 'Test client'
      inputs:
        command: 'custom'
        workingDir: 'client'
        customCommand: 'run test'

    - task: PublishCodeCoverageResults@1
      displayName: 'Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: 'client/coverage/cobertura-coverage.xml'

    - task: Npm@1
      displayName: 'ESLint Code analysis'
      inputs:
        command: 'custom'
        workingDir: 'client'
        customCommand: 'run lint'
      
